### ISSUE TITLE
При создании нового пользователя генерировать пароль на основе шаблона или брать из доп атрибута в LDAP

### ISSUE THREAD

**Issue by matveevandrey** [mikopbx/ModuleLdapSync#7]
Сейчас при синхронизации из AD пароль пользователя в MikoPBX создается автоматически и нет возможности получить список поьзователей/паролей для последующего скармливания в автопровиженинг аппаратов кроме как врручную проходить по списку пользователей и копировать/вставлять пароль, Для инсталяций с большим количеством внутренних номеров это, согласитесь, не вариант

**Comment by jorikfon** [comment]
Будем брать из дополнительного атрибута.
